### PR TITLE
[REVIEW] Fix NVStringsImpl setMemoryBuffer memory leak

### LINKED ISSUE #243: [BUG] NVStringsImpl.setMemoryBuffer memory leak
if NVstringsImpl object memory buffer isn't empty, setMemoryBuffer will lead to the memory leak when new memory buffer is assigned and old memory buffer isn't free.

### PR DESCRIPTION
**Pull request by JinHai-CN**
Fix #243

### CODE REVIEW

**Comment by GPUtester** [comment]
Can one of the admins verify this patch?

**Comment by JinHai-CN** [comment]
#244

**Comment by JinHai-CN** [comment]
#244

**Comment by kkraus14** [comment]
ok to test

**Comment by JinHai-CN** [comment]
Currently, no such condition, but once some guy use the API when memory buffer isn't empty. It's will be very hard to find the memory leak.

**Comment by davidwendt** [comment]
This condition will not occur and the logic is incorrect. There is no need to fix anything here.

**Pull request closed without merging**
