### PR TITLE
Breaking up nvstrings ipc object

### PR DESCRIPTION
**Pull request by rommelDB**
While the current approach is simpler and avoids adding conversion functions, using such python functions could be tricky for python users. For instance, to get the values from a bytearrary after calling get_ipc_data() now wouldn't need to do any extra calculations.

### CODE REVIEW

**Comment by davidwendt** [comment]
Do python users need to access the individual elements of the `ipc_transfer` structure?
It would seem the only parts of the code that need to access individual items is in C/C++ code.

**Comment by rommelDB** [comment]
> Do python users need to access the individual elements of the `ipc_transfer` structure?
> It would seem the only parts of the code that need to access individual items is in C/C++ code.

Yes, i.e. our use case needs to access the individual elements in order to be sent to another module. Instead of sending a single array of bytes we are preferring to send and receive the elements logically separated.

**Comment by davidwendt** [comment]
Can you explain this a little more?  How would the individual items even be used inside of Python? Again, it seems calls to C++ would be necessary to make any use of them.

**Comment by rommelDB** [comment]
I think I said it wrong. Inside of Python we don't need to make any use of them except for them to be sent to another module. So the IPC data would be sent as a set of 5 elements instead of a single byte array.

**Comment by davidwendt** [comment]
Ok. Then why not send a single byte array instead of 5 elements that contain byte-arrays?
You could create a single element of one byte-array.

**Comment by rommelDB** [comment]
Thanks, David, we just followed your suggestion.

**Pull request closed without merging**
