### PR TITLE
[REVIEW] Added Porter Stemmer measure method

### PR DESCRIPTION
**Pull request by davidwendt**
Added C++ method in NVText to compute measure for the Porter Stemmer algorithm.

### CODE REVIEW

**Comment by mike-wendt** [comment]
rerun tests

**Comment by fynv** [comment]
LGTM

**Comment by VibhuJawa** [comment]
Not sure , i  am the correct person to review this as there is no python code. 

Please feel free to merge .

**Comment by davidwendt** [comment]
Thanks Vibhu. I should have referenced #361 where you asked for the `measure` method to be implemented in C++. I'm not really sure the best way to expose through Python in what you are planning here. Just wanted to know the C++ API is ready here whenever you need to call it.

**Pull request merged**
